Documentation for 1.4
ExpressGateway/express-gateway.io pull request #171
Opened 2017-11-15 18:42 UTC by XVincentX

Connect #170 
Closes #170

2017-11-16 22:02 UTC, altsang requested changes
should mention that `app_name` has to be unique by user but that across an EG instance there may be duplicate `app_names` - bsst place to include this info?

2017-11-16 22:02 UTC, altsang commented on docs/admin/policies/index.md
> +### Enables a policiy
`policy`

2017-11-16 22:02 UTC, altsang commented on docs/configuration/system.config.yml/db.md
> +- Ideal for development
`Ideal for development and demos`

2017-11-21 13:44 UTC, DrMegavolt commented on docs/policies/proxy.md
> +* `static`: This strategy routes each client request to the fixed assigned `url`
this is just a technical detail how it is implemented. This is not a load balancing strategy.

2017-11-21 13:46 UTC, DrMegavolt commented on docs/admin/policies/index.md
> +##### Request: `GET /policies`
Is there are doc for pipelines/apiEndpoints/ServiceEndpoints ?

2017-11-21 13:48 UTC, XVincentX commented on docs/policies/proxy.md
> +* `static`: This strategy routes each client request to the fixed assigned `url`
Shall I remove it?

2017-11-21 13:49 UTC, DrMegavolt commented on docs/policies/proxy.md
> +* `static`: This strategy routes each client request to the fixed assigned `url`
yes, I'd remove it

2017-11-21 13:50 UTC, XVincentX commented
Ok, done!

2017-11-21 14:27 UTC, XVincentX commented on docs/admin/policies/index.md
> +##### Request: `GET /policies`
That is still missing, unfortunately.

2017-11-21 17:22 UTC, merged