Fix log policy and reword admin api introduction
ExpressGateway/express-gateway.io pull request #191
Opened 2018-01-18 15:26 UTC by XVincentX

connect #190

2018-01-18 16:14 UTC, DrMegavolt commented on docs/admin/index.md
> -### Core Entities
why removed ?

2018-01-18 17:25 UTC, XVincentX commented on docs/admin/index.md
> -### Core Entities
The paragraph I removed is a trimmed down (and old) version of what we have here: https://www.express-gateway.io/docs/consumer-management and couple of other links.

I'd rather add a link saying "To get more information on core entities, please see …, …, …)

2018-01-18 18:14 UTC, altsang requested changes

2018-01-18 18:14 UTC, altsang commented on docs/admin/index.md
>  Note: in the future the Admin API will also allow configuration of gateway entities such as pipeline and policy
we want to remove this as well right? no longer true - the admin API does do pipeline/policy manipulation as of now

2018-01-18 18:15 UTC, XVincentX commented on docs/admin/index.md
>  Note: in the future the Admin API will also allow configuration of gateway entities such as pipeline and policy
Gosh, true

2018-01-24 09:54 UTC, XVincentX commented on docs/admin/index.md
> -### Core Entities
Actually we do not have such thing. I'll restore it.

2018-01-24 09:58 UTC, XVincentX commented
@DrMegavolt Please have another look when you've got time, thanks!

2018-01-24 17:31 UTC, altsang approved these changes

2018-01-24 18:02 UTC, merged