Env support
ExpressGateway/express-gateway.io pull request #195
Opened 2018-01-27 14:06 UTC by XVincentX

2018-01-27 16:40 UTC, DrMegavolt approved these changes
LGTM

2018-01-27 17:00 UTC, altsang requested changes

2018-01-27 17:00 UTC, altsang commented on docs/configuration/index.md
> +You can use environment variables in configuration files; they follow the same syntax of `docker-compose.yml` files.
can we do [Docker Compose YAML](https://docs.docker.com/compose/environment-variables/)

2018-01-27 17:00 UTC, altsang commented on docs/faq.md
> +Yes, you can! We have borrowed the same syntax that `docker-compose.yml` files are using. Check out the relative
[Docker Compose YAML](https://docs.docker.com/compose/environment-variables/)

2018-01-28 10:59 UTC, XVincentX commented
@altsang Done!

2018-01-28 18:08 UTC, merged