OpenAPI announcement blog post — Connect LunchBadger/marketing#25 Closes Connect LunchBadger/marketing#25
ExpressGateway/express-gateway.io pull request #261
Opened 2018-08-08 14:22 UTC by XVincentX

The idea would be to spread this blog post a little bit with our social media as well as our Gitter channel and see if we can gather any feedback around.

2018-08-10 22:24 UTC, kevinswiber requested changes
@XVincentX This looks great!  Just a couple of letters need to be removed, and I think this is golden.

2018-08-10 22:24 UTC, kevinswiber commented on _posts/2018-08-14-openapi-support-eg.markdown
> +#### Connectivity informations
s/informations/information

2018-08-10 22:24 UTC, kevinswiber commented on _posts/2018-08-14-openapi-support-eg.markdown
> +We can use the connectivity informations for server target to configure the host of all the [apiEndpoints][apiEndpoints]. In this way we can make sure Express Gateway will receive connections exclusi
s/informations/information

2018-08-13 16:03 UTC, snowcrash007 commented
Let me know when it's published and I can get it up on our channels.

2018-08-13 16:05 UTC, XVincentX commented
@snowcrash007 I can publish right now.

2018-08-13 17:03 UTC, merged