[UI] share icons css
ExpressGateway/express-gateway.io pull request #300
Opened 2019-03-29 15:45 UTC by kolbinski

2019-03-29 15:58 UTC, altsang approved these changes

2019-03-29 20:19 UTC, XVincentX requested changes

2019-03-29 20:19 UTC, XVincentX commented on _includes/share.html
> +      {% include social-facebook-blue.svg %}
Can we remove the old icons, if not used?

2019-03-29 22:10 UTC, kolbinski commented on _includes/share.html
> +      {% include social-facebook-blue.svg %}
No, az old icons are used in the page footer.

2019-04-11 17:42 UTC, XVincentX approved these changes

2019-04-11 17:45 UTC, merged