post seo tag fixes
ExpressGateway/express-gateway.io pull request #309
Opened 2019-04-18 16:03 UTC by altsang

2019-04-19 14:18 UTC, XVincentX requested changes
2 images out of 4 are not used and we already have got a meta image; let's replace that one instead of adding yet another one.

2019-04-19 14:18 UTC, XVincentX commented on _includes/insert-to-head.html
> +    <meta property="og:image" content="{{ site.url }}/{{ page.header-img }}" />
We already have a `expressgateway_metaimage.png`, let's replace that one instead of adding a new one.

2019-04-19 16:45 UTC, altsang commented on _includes/insert-to-head.html
> +    <meta property="og:image" content="{{ site.url }}/{{ page.header-img }}" />
I'll check with @shashikan8h , i think the reason for introducing a new one is that the main logo is used and that it's horizontally oriented for image inclusion in things like twitter cards, but I dunno

2019-04-19 16:45 UTC, altsang commented
> 2 images out of 4 are not used and we already have got a meta image; let's replace that one instead of adding yet another one.

which 2 images aren't used?

2019-04-22 04:16 UTC, altsang commented on _includes/insert-to-head.html
> +    <meta property="og:image" content="{{ site.url }}/{{ page.header-img }}" />
I updated `expressgateway_metaimage.png` with the logo file - @shashikan8h wants to make everything consistent

2019-04-24 00:37 UTC, XVincentX approved these changes

2019-04-24 00:37 UTC, merged